# Generated by Django 3.0.6 on 2020-05-27 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPost',
        ),
    ]
