# Generated by Django 3.0.6 on 2020-05-29 09:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0005_auto_20200529_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfollowing',
            old_name='follower_user_id',
            new_name='user_id',
        ),
        migrations.AlterUniqueTogether(
            name='userfollowing',
            unique_together={('user_id', 'following_user_id')},
        ),
    ]
