# Generated by Django 3.0.6 on 2020-05-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20200524_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.EmailField(default='', max_length=55, unique=True, verbose_name='username'),
        ),
    ]
