# Generated by Django 3.0.6 on 2020-05-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20200524_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.TextField(default='', max_length=55, unique=True, verbose_name='username'),
        ),
    ]
