# Generated by Django 3.0.6 on 2020-05-24 14:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.TextField(default=django.utils.timezone.now, max_length=55, unique=True, verbose_name='user name'),
            preserve_default=False,
        ),
    ]
