# Generated by Django 3.0.6 on 2020-05-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.TextField(default='admin', max_length=55, unique=True, verbose_name='username'),
        ),
    ]
