# Generated by Django 3.0.6 on 2020-05-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_auto_20200524_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.SlugField(max_length=55, unique=True, verbose_name='username'),
        ),
    ]
