# Generated by Django 3.0.6 on 2020-05-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_auto_20200524_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.SlugField(max_length=55, verbose_name='username'),
        ),
    ]
