# Generated by Django 3.0.6 on 2020-05-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_auto_20200526_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=55, unique=True, verbose_name='username'),
        ),
    ]
