# Generated by Django 3.0.6 on 2020-05-29 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_userfollowing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFollowing',
        ),
    ]
